### ISSUE TITLE
ProteaLang or SagaScript?

### ISSUE THREAD

**Issue by mr-cheffy** [NoxVentura/ProteaLang#1]
Please update the README or the repo's name

(love this idea)

:)

**Comment by nexovolta** [comment]
SagaScript now! I wanted to honor the spirit of JavaScript so I named it that

I tried settling on the language name for a bit and kept switching between these two.

**Comment by nexovolta** [comment]
Actually not yet. It's hard naming a language so I decided to keep it to Protea.

The word _protean_ means versatile, and changes frequently. In a way, it's just like JavaScript.

**Comment by mr-cheffy** [comment]
👍🏽
